#Application Properties
#Application Properties
mspost:
  application:
    name: ms-post
    datasource:
      host: ""
      database: ""
      username: ""
      password: ""
      protocol: mongodb
      options: '?authSource=ms-auth'

    security:
      jwt-token:
        secret: ""

      corsConfig:
        allowed-origins: "*"
        allowed-methods: "*"
        allowed-headers: "*"
        exposed-headers: "Authorization"
        allow-credentials: true
        max-age: 1800
    kafka:
      servers: 3.223.152.25:9092
      topics:
        output:
          logs: com-fyself-dev-logs
    server:
      port: 8080

application:
  name: ${mspost.application.name}
  datasource:
    host: ${mspost.application.datasource.host}
    database: ${mspost.application.datasource.database}
    username: ${mspost.application.datasource.username}
    password: ${mspost.application.datasource.password}
    protocol: ${mspost.application.datasource.protocol}
    options: ${mspost.application.datasource.options}

  security:
    jwt-token:
      secret: ${mspost.application.security.jwt-token.secret}

    corsConfig:
      allowed-origins: ${mspost.application.security.corsConfig.allowed-origins}
      allowed-methods: ${mspost.application.security.corsConfig.allowed-methods}
      allowed-headers: ${mspost.application.security.corsConfig.allowed-headers}
      exposed-headers: ${mspost.application.security.corsConfig.exposed-headers}
      allow-credentials: ${mspost.application.security.corsConfig.allow-credentials}
      max-age: ${mspost.application.security.corsConfig.max-age}
  kafka:
    servers: ${mspost.application.kafka.servers}

    topics:
      output:
        logs: ${mspost.application.kafka.topics.output.logs}


  server:
    port: ${mspost.application.server.port}



spring:
  data:
    mongodb:
      uri: ${application.datasource.protocol}://${application.datasource.username}:${application.datasource.password}@${application.datasource.host}/${application.datasource.database}${application.datasource.options}

  jpa:
    open-in-view: false
  mvc:
    favicon:
      enabled: false
    servlet:
      load-on-startup: 1
  output:
    ansi:
      enabled: always

#Server Properties
server:
  port: ${application.server.port}
